[package]
name = "day04"
version = "0.1.0"
authors = ["Thorsten Mürell <thorsten@muerell.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
strum = { version = "0.20", features = ["derive"] }
lazy_static = "1.4.0"
